window.SUPABASE_URL='https://iqwwoihiiyrtypyqzhgy.supabase.co';window.SUPABASE_ANON_KEY='sb_publishable_m4WcF4gmkj1olAj95HMLlA_4yKqPFXm';if(!window.supabaseClient){window.supabaseClient=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY,{auth:{persistSession:false},realtime:{params:{eventsPerSecond:10}}});console.log('✅ Cliente Supabase inicializado');}
window.configGlobal={tasa_cambio:400,tasa_efectiva:400,aumento_diario:0,aumento_acumulado:0,aumento_activo:false,aumento_detenido:false,fecha_ultimo_aumento:null,ultima_actualizacion:null,admin_password:'654321',recovery_email:'admin@sakisushi.com',alerta_stock_minimo:5};
window.cargarConfiguracion=async()=>{try{const{data,error}=await window.supabaseClient.from('config').select('*').eq('id',1).single();if(error)throw error;if(data)window.configGlobal={...window.configGlobal,...data};return window.configGlobal;}catch(error){console.error('Error cargando configuración:',error);return window.configGlobal;}};
window.subirImagenPlatillo=async(archivoImagen,carpetaAdicional='')=>{try{if(!archivoImagen)return{success:false,error:'No se proporcionó archivo'};const tipoValido=['image/jpeg','image/png','image/jpg','image/webp','image/gif'];if(!tipoValido.includes(archivoImagen.type))return{success:false,error:'Tipo de archivo no válido'};if(archivoImagen.size>5*1024*1024)return{success:false,error:'El archivo es demasiado grande. Máximo 5MB'};const timestamp=Date.now(),random=Math.random().toString(36).substring(2,8),extension=archivoImagen.name.split('.').pop(),nombreArchivo=`${timestamp}_${random}.${extension}`,ruta=carpetaAdicional?`${carpetaAdicional}/${nombreArchivo}`:nombreArchivo;const{data,error}=await window.supabaseClient.storage.from('imagenes-platillos').upload(ruta,archivoImagen,{cacheControl:'3600',upsert:false,contentType:archivoImagen.type});if(error)throw error;const{data:urlData}=window.supabaseClient.storage.from('imagenes-platillos').getPublicUrl(ruta);return{success:true,path:ruta,url:urlData.publicUrl};}catch(error){return{success:false,error:error.message}}};
window.eliminarImagenPlatillo=async(urlImagen)=>{try{if(!urlImagen)return{success:true};const bucketIndex=urlImagen.indexOf('/public/imagenes-platillos/');if(bucketIndex===-1)return{success:true};const rutaRelativa=urlImagen.substring(bucketIndex+'/public/imagenes-platillos/'.length);if(!rutaRelativa)return{success:true};const{error}=await window.supabaseClient.storage.from('imagenes-platillos').remove([rutaRelativa]);if(error)throw error;return{success:true};}catch(error){return{success:false,error:error.message}}};
window.subirComprobante=async(file,tipo,onProgress)=>{try{if(!file)throw new Error('No se proporcionó archivo');const tipoValido=['image/jpeg','image/png','image/jpg','image/webp','image/gif'];if(!tipoValido.includes(file.type))throw new Error('Tipo de archivo no válido');if(file.size>5*1024*1024)throw new Error('El archivo es demasiado grande. Máximo 5MB');const timestamp=Date.now(),nombreArchivo=`${timestamp}_${file.name.replace(/[^a-zA-Z0-9.]/g,'_')}`,ruta=`${tipo}/${nombreArchivo}`;const{data,error}=await window.supabaseClient.storage.from('comprobantes').upload(ruta,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;const{data:urlData}=window.supabaseClient.storage.from('comprobantes').getPublicUrl(ruta);if(onProgress)onProgress({loaded:file.size,total:file.size,percent:100});return{success:true,url:urlData.publicUrl};}catch(error){return{success:false,error:error.message}}};
window.formatBs=m=>new Intl.NumberFormat('es-VE',{style:'currency',currency:'VES',minimumFractionDigits:2}).format(m).replace('VES','Bs.');
window.formatUSD=m=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2}).format(m);
window.generarId=(prefix='')=>`${prefix}${Date.now()}_${Math.random().toString(36).substring(2,9)}`;
window.validarTelefono=t=>{const s=t.replace(/\D/g,'');return/^(0412|0414|0424|0416|0426|0418|0422|0212|0234|0241|0243|0246|0251|0254|0255|0257|0261|0264|0265|0268|0271|0273|0274|0275|0276|0281)\d{7}$/.test(s);};
window.validarReferencia=r=>r.replace(/\D/g,'').length===6;
window.usdToBs=(u,t)=>u*(t||window.configGlobal.tasa_efectiva||400);
window.bsToUsd=(b,t)=>b/(t||window.configGlobal.tasa_efectiva||400);
window.stockCache={data:{},lastUpdate:0,duration:5000,get(id){if(Date.now()-this.lastUpdate>this.duration)this.clear();return this.data[id];},set(id,val){this.data[id]=val;this.lastUpdate=Date.now();},clear(){this.data={};this.lastUpdate=Date.now();},invalidate(){this.data={};this.lastUpdate=0;}};
window.parroquiasDelivery=[{nombre:"San Bernardino",precioUSD:2},{nombre:"San José",precioUSD:2},{nombre:"San Agustín",precioUSD:2},{nombre:"Candelaria",precioUSD:2},{nombre:"San Juan",precioUSD:3},{nombre:"Catedral",precioUSD:3},{nombre:"Santa Rosalía",precioUSD:3},{nombre:"El Recreo",precioUSD:4},{nombre:"La Candelaria",precioUSD:2},{nombre:"San Pedro",precioUSD:4},{nombre:"El Paraíso",precioUSD:4},{nombre:"La Vega",precioUSD:4},{nombre:"El Valle",precioUSD:5},{nombre:"Coche",precioUSD:5},{nombre:"Caricuao",precioUSD:7},{nombre:"Antímano",precioUSD:7},{nombre:"Macarao",precioUSD:7},{nombre:"23 de Enero",precioUSD:4},{nombre:"La Pastora",precioUSD:3},{nombre:"Altagracia",precioUSD:3},{nombre:"Santa Teresa",precioUSD:3},{nombre:"Santa Rosalía de Palermo",precioUSD:3},{nombre:"Chacao",precioUSD:5},{nombre:"Leoncio Martínez",precioUSD:6},{nombre:"Petare",precioUSD:6},{nombre:"La Dolorita",precioUSD:6},{nombre:"Fila de Mariches",precioUSD:6},{nombre:"Caucagüita",precioUSD:7},{nombre:"El Cafetal",precioUSD:6},{nombre:"Las Minas",precioUSD:5},{nombre:"Nuestra Señora del Rosario",precioUSD:7},{nombre:"Sucre",precioUSD:7},{nombre:"El Junquito",precioUSD:7}];
window.categoriasMenu={Entradas:[],Sushi:[],Rolls:["Rolls Fríos de 10 piezas","Rolls Tempura de 12 piezas"],"Tragos y bebidas":[],Pokes:[],Ensaladas:[],"Comida China":["Arroz Chino","Arroz Cantones","Chopsuey","Lomey","Chow Mein","Fideos de Arroz","Tallarines Cantones","Mariscos","Foo Yong","Sopas","Entremeses"],"Comida Japonesa":["Yakimeshi","Yakisoba","Pasta Udon","Churrasco"],"Ofertas Especiales":[],"Para Niños":[],"Combo Ejecutivo":[]};
console.log('✅ supabase-config.js cargado');
